# -----------------------------------------------------------------------------
# Configurações genéricas
# O controle da Key e Nome do projeto serão feitos pelo Makefile
# -----------------------------------------------------------------------------

sonar.sourceEncoding=UTF-8

# Pastas relevantes para análise
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
